export default function HomePage() {
  return (
    <main className="min-h-screen overflow-hidden bg-[#090d12] text-[#e8f0f2]">
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 text-sm md:px-10"><a href="/" className="flex items-center gap-3 font-bold tracking-tight"><span className="grid h-8 w-8 place-items-center bg-[#c7f36b] text-xs text-[#090d12]">A</span> AM/OS <span className="hidden font-normal text-[#788890] sm:inline">merchant infrastructure</span></a><div className="flex items-center gap-6"><a href="/checkout" className="text-[#9aabb2] transition hover:text-white">Buyer simulator</a><a href="/dashboard" className="border border-[#33434a] px-4 py-2 transition hover:border-[#c7f36b] hover:text-[#c7f36b]">Open console ↗</a></div></nav>
      <section className="relative mx-auto grid max-w-7xl items-center gap-16 px-6 pb-24 pt-20 md:px-10 md:pt-28 lg:grid-cols-[1.05fr_0.95fr]"><div className="absolute -left-40 top-0 h-96 w-96 rounded-full bg-[#21d4fd]/10 blur-3xl" /><div className="relative"><div className="flex items-center gap-3 text-[11px] font-bold uppercase tracking-[0.24em] text-[#c7f36b]"><span className="h-2 w-2 animate-pulse rounded-full bg-[#c7f36b]" /> System online · Test environment</div><h1 className="mt-8 max-w-3xl text-6xl font-bold leading-[0.92] tracking-[-0.06em] md:text-8xl">The operating layer for <span className="text-[#21d4fd]">agentic commerce.</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-[#9aabb2]">Make your catalog legible to AI buyers. Let agents transact with guardrails. See every decision in real time.</p><div className="mt-10 flex flex-wrap gap-3"><a href="/dashboard" className="bg-[#c7f36b] px-6 py-3 font-bold text-[#090d12] transition hover:bg-white">Launch merchant console</a><a href="/checkout" className="border border-[#33434a] px-6 py-3 text-[#d4dfe2] transition hover:border-[#21d4fd] hover:text-[#21d4fd]">Run buyer simulation</a></div></div><div className="relative border border-[#26353d] bg-[#101820] p-5 shadow-[0_0_80px_rgba(33,212,253,0.08)]"><div className="flex items-center justify-between border-b border-[#26353d] pb-4 text-[10px] uppercase tracking-[0.18em] text-[#788890]"><span>Live policy monitor</span><span className="text-[#c7f36b]">● protected</span></div><div className="mt-8 grid grid-cols-2 gap-px bg-[#26353d]"><div className="bg-[#101820] p-5"><p className="text-[10px] uppercase tracking-widest text-[#788890]">Agent actions</p><p className="mt-3 text-4xl font-bold">24<span className="text-lg text-[#788890]"> today</span></p></div><div className="bg-[#101820] p-5"><p className="text-[10px] uppercase tracking-widest text-[#788890]">Policy blocks</p><p className="mt-3 text-4xl font-bold text-[#ffb86b]">17</p></div></div><div className="mt-6 space-y-3 font-mono text-xs"><p className="flex gap-3 text-[#788890]"><span className="text-[#21d4fd]">08:42:01</span><span>catalog.query</span><span className="ml-auto text-[#c7f36b]">allowed</span></p><p className="flex gap-3 text-[#788890]"><span className="text-[#21d4fd]">08:42:05</span><span>order.create</span><span className="ml-auto text-[#ffb86b]">blocked</span></p><p className="flex gap-3 text-[#788890]"><span className="text-[#21d4fd]">08:42:07</span><span>audit.write</span><span className="ml-auto text-[#c7f36b]">recorded</span></p></div><div className="mt-8 h-2 overflow-hidden bg-[#26353d]"><div className="h-full w-3/4 bg-gradient-to-r from-[#21d4fd] to-[#c7f36b]" /></div><div className="mt-2 flex justify-between text-[10px] text-[#788890]"><span>Risk engine capacity</span><span>75%</span></div></div></section>
      <section className="border-y border-[#26353d] bg-[#0d1319]"><div className="mx-auto grid max-w-7xl gap-px bg-[#26353d] md:grid-cols-3"><div className="bg-[#0d1319] p-8 md:p-10"><p className="font-mono text-sm text-[#21d4fd]">01 / DISCOVER</p><h2 className="mt-5 text-2xl font-bold">Agent-readable by default.</h2><p className="mt-3 leading-7 text-[#788890]">Structured catalog data that gives autonomous buyers reliable context.</p></div><div className="bg-[#0d1319] p-8 md:p-10"><p className="font-mono text-sm text-[#21d4fd]">02 / DECIDE</p><h2 className="mt-5 text-2xl font-bold">Policy before payment.</h2><p className="mt-3 leading-7 text-[#788890]">Spending limits and rules run before a Razorpay order exists.</p></div><div className="bg-[#0d1319] p-8 md:p-10"><p className="font-mono text-sm text-[#21d4fd]">03 / PROVE</p><h2 className="mt-5 text-2xl font-bold">Every action accounted for.</h2><p className="mt-3 leading-7 text-[#788890]">A decision log merchants can inspect, explain, and trust.</p></div></div></section>
      <footer className="mx-auto flex max-w-7xl flex-wrap justify-between gap-4 px-6 py-8 text-xs text-[#788890] md:px-10"><span>AM/OS · built for the agent economy</span><span>FastAPI · SQLite · Groq · Razorpay Test Mode</span></footer>
    </main>
  );
}
