"use client";
import { useEffect, useState } from "react";
import { ProductCard } from "../../components/ProductCard";
import { StatCard } from "../../components/StatCard";
const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
type Product = { id: number; name: string; category: string; description: string; price_paise: number; stock: number };
type Audit = { id: number; action: string; amount_paise: number; decision: string; explanation: string; agent_id: string };
export default function DashboardPage() {
  const [products, setProducts] = useState<Product[]>([]); const [logs, setLogs] = useState<Audit[]>([]); const [revenue, setRevenue] = useState(0); const [message, setMessage] = useState("");
  const refresh = () => { Promise.all([fetch(`${API}/api/products`).then(r => r.json()), fetch(`${API}/api/audit`).then(r => r.json()), fetch(`${API}/api/audit/metrics`).then(r => r.json())]).then(([items, audit, metrics]) => { setProducts(items); setLogs(audit); setRevenue(metrics.revenue_paise); }); };
  useEffect(() => { refresh(); }, []);
  const buy = (id: number) => fetch(`${API}/api/orders`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ product_id: id, quantity: 1, agent_id: "dashboard-demo" }) }).then(async r => { const data = await r.json(); setMessage(r.ok ? `Test order ${data.razorpay_order_id} created.` : data.detail?.message || "Order rejected."); refresh(); });
  return <main className="mx-auto max-w-6xl px-6 py-12 md:px-10"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.2em] text-clay">Merchant workspace</p><h1 className="mt-3 text-5xl">Control room</h1></div><a href="/checkout" className="border-b border-clay pb-1 text-clay">Open buyer checkout →</a></header>{message && <p className="mt-6 border-l-2 border-clay bg-white/50 p-4 text-sm">{message}</p>}<section className="mt-14 grid gap-8 border-y border-ink/15 py-6 sm:grid-cols-3"><StatCard label="Products" value={String(products.length)} /><StatCard label="Paid revenue" value={`₹${(revenue / 100).toLocaleString("en-IN")}`} /><StatCard label="Audit events" value={String(logs.length)} /></section><section className="mt-14"><h2 className="text-3xl">Catalog</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{products.map(product => <ProductCard key={product.id} product={product} onBuy={buy} />)}</div></section><section className="mt-16"><h2 className="text-3xl">Audit trail</h2><div className="mt-6 overflow-x-auto border border-ink/15 bg-white/35"><table className="w-full text-left text-sm"><thead className="border-b border-ink/15 text-xs uppercase tracking-wider text-ink/55"><tr><th className="p-4">Agent</th><th className="p-4">Action</th><th className="p-4">Amount</th><th className="p-4">Decision</th><th className="p-4">Explanation</th></tr></thead><tbody>{logs.map(log => <tr key={log.id} className="border-b border-ink/10"><td className="p-4">{log.agent_id}</td><td className="p-4">{log.action}</td><td className="p-4">₹{(log.amount_paise / 100).toLocaleString("en-IN")}</td><td className={`p-4 font-bold ${log.decision === "approved" ? "text-green-700" : "text-clay"}`}>{log.decision}</td><td className="max-w-md p-4 text-ink/65">{log.explanation}</td></tr>)}</tbody></table></div></section></main>;
}
